#!/bin/bash

# This script is a bar for dwm using xsetroot.
# To run it write in your .xinitrc somethong like this:
# bash ~/path/to/dwm_bar &

#Bar
datt(){
    dat="$(date --utc +%H:%M:%S)"
    echo -e "$dat"
}

#batt(){
#    bat="$(cat /sys/class/power_supply/BAT1/capacity)"
#    echo -e " $bat" #                  :D  
#}

cpu(){
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    echo -e "Cpu $cpu%"
}

memo(){
    #mem=`free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
    mem=`free | awk '/Mem/ {printf "%d/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
    echo -e "Mem $mem"
}

while true; do
    xsetroot -name "| $(cpu) | $(memo) | $(datt) |  |"
    sleep 1s #Update time
done &
